name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      env:
        IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/runpod-voxcpm
      run: |
        docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s) --tag ${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.IMAGE_NAME }}:latest
    - name: Run Tests
      uses: runpod/test-runner@v2.1.0
      with:
        image-tag: ghcr.io/${{ github.repository_owner }}
        runpod-api-key: ${{ secrets.RUNPOD_API_KEY }} # Add your API key to a GitHub secret
        test-filename: .github/tests.json
        request-timeout: 300